name: Events

on:
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: login
        run: echo "${{ github.event.sender.login }}"
      - name: id
        run: echo "${{ github.event.sender.id }}"

